title: BRGSIL
url: "https://brgsil.github.io"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/brgsil"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Animations"
   link: "/animations/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
