title: Bruno Guedes da Silva
url: "https://brgsil.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer:
  email: b203657@dac.unicamp.br
  github: brgsil
  url: "https://github.com/ankitsultana/researcher"
  text: "Page design template by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
 - name: "Animations"
   link: "animations"
 - name: "Resume"
   link: "resume.pdf"
